title: Mutual TLS
description: |-
  This examples demonstrates a basic embedded server and client
  [mkcert](https://github.com/FiloSottile/mkcert) tool using
  the commands below to generate the necessary server and client certs.
  ```sh
  mkcert \
    -key-file key.pem \
    -cert-file cert.pem \
    localhost

  mkcert \
    -client \
    -key-file client-key.pem \
    -cert-file client-cert.pem \
    localhost

  ln -s /root/.local/share/mkcert/rootCA.pem ca.pem
  ```